<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24898" started-at="2020-11-29T03:25:30Z" finished-at="2020-11-29T03:25:55Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="24898" started-at="2020-11-29T03:25:30Z" finished-at="2020-11-29T03:25:55Z">
      <class name="com.learnautomation.framework.testcases.LoginTest">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="startBrowser" is-config="true" duration-ms="11287" started-at="2020-11-29T03:25:30Z" finished-at="2020-11-29T03:25:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="setup" is-config="true" duration-ms="21" started-at="2020-11-29T03:25:43Z" finished-at="2020-11-29T03:25:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginWithAdmin(java.lang.String, java.lang.String)[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="loginWithAdmin" duration-ms="7194" started-at="2020-11-29T03:25:43Z" data-provider="LoginData" finished-at="2020-11-29T03:25:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithAdmin -->
        <test-method status="FAIL" signature="loginWithAdmin(java.lang.String, java.lang.String)[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="loginWithAdmin" duration-ms="1910" started-at="2020-11-29T03:25:50Z" data-provider="LoginData" finished-at="2020-11-29T03:25:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Maven]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[TestNg]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.learnautomation.framework.pages.LoginPage.loginToApplication(LoginPage.java:46)
at com.learnautomation.framework.testcases.LoginTest.loginWithAdmin(LoginTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithAdmin -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="setup" is-config="true" duration-ms="0" started-at="2020-11-29T03:25:50Z" finished-at="2020-11-29T03:25:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="setup" is-config="true" duration-ms="1" started-at="2020-11-29T03:25:52Z" finished-at="2020-11-29T03:25:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginWithAdmin(java.lang.String, java.lang.String)[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="loginWithAdmin" duration-ms="1416" started-at="2020-11-29T03:25:52Z" data-provider="LoginData" finished-at="2020-11-29T03:25:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AutoIT]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Git]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.learnautomation.framework.pages.LoginPage.loginToApplication(LoginPage.java:46)
at com.learnautomation.framework.testcases.LoginTest.loginWithAdmin(LoginTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithAdmin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.learnautomation.framework.testcases.LoginTest@4f83df68]" name="closeBrowser" is-config="true" duration-ms="1208" started-at="2020-11-29T03:25:53Z" finished-at="2020-11-29T03:25:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.learnautomation.framework.testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
